serverAddr = "frp.example.com"
serverPort = 7000
token = "myfrptoken"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000

[[proxies]]
name = "http"
type = "http"
localIP = "192.168.1.100"
localPort = 80
customDomains = ["example.com"]
