port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "0.0.0.0"
mode: Rule
log-level: info

proxies:
  - name: "默认节点"
    type: vmess
    server: "1.2.3.4"
    port: 443
    uuid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    alterId: 0
    cipher: "auto"
    network: ws
    ws-path: "/ws"
    ws-headers:
      Host: "1.2.3.4"

proxy-groups:
  - name: "选择节点"
    type: select
    proxies:
      - "默认节点"
      - "DIRECT"

rules:
  - "DOMAIN-SUFFIX,google.com,选择节点"
  - "GEOIP,CN,DIRECT"
  - "MATCH,选择节点"
