name: Build Orange Pi Zero Firmware

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TZ: Asia/Shanghai
      OPENWRT_TARGET: sunxi/cortexa7
      OPENWRT_IMAGE_NAME: openwrt-orangepi-zero

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses5-dev \
            gawk \
            git \
            gettext \
            libssl-dev \
            xsltproc \
            unzip \
            wget \
            python3 \
            python3-dev \
            python3-venv \
            python3-pip

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile firmware
        run: |
          make defconfig
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OPENWRT_IMAGE_NAME }}
          path: bin/targets/${{ env.OPENWRT_TARGET }}/*.img
